language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
sudo: false
matrix:
  include:
    - rvm: 1.8.7
      gemfile: Gemfiles/Gemfile.1.8.7
    - rvm: 1.9.2
      gemfile: Gemfiles/Gemfile.1.9.2
